### PR TITLE
Added possibility to purge influxDB backups after uploaded to cloud

### PR DESCRIPTION
**Pull request by Xartos**
Fix for the issue of the ever increasing backup volume.

I have not tested this yet, hence the draft. I just want some quick feedback.

### CODE REVIEW

**Review by OlleLarsson — APPROVED** [review]
Nice!

**Comment by OlleLarsson** [comment]
I'm not really sure why anyone would like to keep backups on the pv, for safety perhaps?
I guess that we could ask whether or not it should be default to remove backups localy once they've been pushed to the cloud.

**Comment by Xartos** [comment]
Yea, I don't see any good reason either. But it felt less intrusive if it was, by default, set to false and that the functionality is the same for people already running it. But as you say, let's check with the upstream people.

**Review by lentzi90 — APPROVED** [review]
LGTM

**Comment by viktor-f** [comment]
Fixed upstream https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/templates/backup-cronjob.yaml#L138

**Pull request closed without merging**
